### ISSUE TITLE
Purpose of scraping?

### ISSUE THREAD

**Issue by klokan** [thisismattmiller/scrape-iiif#1]
Hi Matt!

Could you please comment on WHY for WHOM you are scraping the IIIF services here?

Similar scripts can seriously overload the serving infrastructure - and in many cases, the original images are available in a higher quality for download from the institutions.
(for example from the David Rumsey website).

**Comment by thisismattmiller** [comment]
It was for a proof of concept service we were trying out during an IIIF Maps meeting last week at Stanford (expanding on https://github.com/bertspaan/georectify-service). It combines GCPs and mask data with an IIIF endpoint to make a rectified geotiff. 

So maybe SCRAPE was the wrong word here, not using it to harvest images in bulk, but for a real time processes that require a full resolution asset as defined in the IIIF manifest.

I would be great if the manifest had a "direct download" property, because often, as with the Rumsey site, it provides a  `/full/full/0/native.jpg` link but it is not the full res image, so it is impossible to navigate to the full size asset via IIIF endpoint alone.
-Matt

**Comment by klokan** [comment]
There are people like you and others in NYPL and Wikidata behind Georeferencer & OldMapsOnline services - wouldn't it be easier to just talk?
We are keen to hear what guys need - and how we can cooperate and share.

What about to schedule a short video meeting - perhaps also with @bertspaan - maybe after the next IIIF Maps community meeting in 2 weeks (March 11th, 6pm CEST)?

**Comment by bertspaan** [comment]
@klokan: Sounds good, I'll join next week's IIIF maps meeting, we can continue talking afterwards!

**Comment by klokan** [comment]
Great! Looking forward to the meeting @bertspaan !
@thisismattmiller do you think you manage to join too?
